package common

import "testing"

func TestAsciiUnicodePunctuationsCheck(t *testing.T) {
	for _, test := range []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return false for U+0020", input: '\u0019', output: false},
		{name: "should return true for U+0021", input: '!', output: true},
		{name: "should return true for U+0022", input: '"', output: true},
		{name: "should return true for U+0023", input: '#', output: true},
		{name: "should return true for U+0024", input: '$', output: true},
		{name: "should return true for U+0025", input: '%', output: true},
		{name: "should return true for U+0026", input: '&', output: true},
		{name: "should return true for U+0027", input: '\'', output: true},
		{name: "should return true for U+0028", input: '(', output: true},
		{name: "should return true for U+0029", input: ')', output: true},
		{name: "should return true for U+002A", input: '*', output: true},
		{name: "should return true for U+002B", input: '+', output: true},
		{name: "should return true for U+002C", input: ',', output: true},
		{name: "should return true for U+002D", input: '-', output: true},
		{name: "should return true for U+002E", input: '.', output: true},
		{name: "should return true for U+002F", input: '/', output: true},
		{name: "should return false for U+0030", input: '\u0030', output: false},
		{name: "should return false for U+0039", input: '\u0039', output: false},
		{name: "should return true for U+003A", input: ':', output: true},
		{name: "should return true for U+003B", input: ';', output: true},
		{name: "should return true for U+003C", input: '<', output: true},
		{name: "should return true for U+003D", input: '=', output: true},
		{name: "should return true for U+003E", input: '>', output: true},
		{name: "should return true for U+003F", input: '?', output: true},
		{name: "should return true for U+0040", input: '@', output: true},
		{name: "should return false for U+0041", input: '\u0041', output: false},
		{name: "should return false for U+005A", input: '\u005A', output: false},
		{name: "should return true for U+005B", input: '[', output: true},
		{name: "should return true for U+005C", input: '\\', output: true},
		{name: "should return true for U+005D", input: ']', output: true},
		{name: "should return true for U+005E", input: '^', output: true},
		{name: "should return true for U+005F", input: '_', output: true},
		{name: "should return true for U+0060", input: '`', output: true},
		{name: "should return false for U+0061", input: '\u0061', output: false},
		{name: "should return false for U+007A", input: '\u007A', output: false},
		{name: "should return true for U+007B", input: '{', output: true},
		{name: "should return true for U+007C", input: '|', output: true},
		{name: "should return true for U+007D", input: '}', output: true},
		{name: "should return true for U+007E", input: '~', output: true},
		{name: "should return false for U+007F", input: '\u007F', output: false},
	} {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, false, false, false, false))
		})
	}
}

func TestPcUnicodePunctuationsCheck(t *testing.T) {
	for _, test := range []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for LowLine", input: LowLine, output: true},
		{name: "should return true for Undertie", input: Undertie, output: true},
		{name: "should return true for CharacterTie", input: CharacterTie, output: true},
		{name: "should return true for InvertedUndertie", input: InvertedUndertie, output: true},
		{name: "should return true for PresentationFormForVerticalLowLine", input: PresentationFormForVerticalLowLine, output: true},
		{name: "should return true for PresentationFormForVerticalWavyLowLine", input: PresentationFormForVerticalWavyLowLine, output: true},
		{name: "should return true for DashedLowLine", input: DashedLowLine, output: true},
		{name: "should return true for CentrelineLowLine", input: CentrelineLowLine, output: true},
		{name: "should return true for WavyLowLine", input: WavyLowLine, output: true},
		{name: "should return true for FullwidthLowLine", input: FullwidthLowLine, output: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, true, false, false, false, false, false, false))
		})
	}
}

func TestPdUnicodePunctuationsCheck(t *testing.T) {
	for _, test := range []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for HyphenMinus", input: HyphenMinus, output: true},
		{name: "should return true for ArmenianHyphen", input: ArmenianHyphen, output: true},
		{name: "should return true for HebrewPunctuationMaqaf", input: HebrewPunctuationMaqaf, output: true},
		{name: "should return true for CanadianSyllabicsHyphen", input: CanadianSyllabicsHyphen, output: true},
		{name: "should return true for MongolianTodoSoftHyphen", input: MongolianTodoSoftHyphen, output: true},
		{name: "should return true for Hyphen", input: Hyphen, output: true},
		{name: "should return true for NonBreakingHyphen", input: NonBreakingHyphen, output: true},
		{name: "should return true for FigureDash", input: FigureDash, output: true},
		{name: "should return true for EnDash", input: EnDash, output: true},
		{name: "should return true for EmDash", input: EmDash, output: true},
		{name: "should return true for HorizontalBar", input: HorizontalBar, output: true},
		{name: "should return true for DoubleObliqueHyphen", input: DoubleObliqueHyphen, output: true},
		{name: "should return true for HyphenwithDiaeresis", input: HyphenwithDiaeresis, output: true},
		{name: "should return true for TwoEmDash", input: TwoEmDash, output: true},
		{name: "should return true for ThreeEmDash", input: ThreeEmDash, output: true},
		{name: "should return true for DoubleHyphen", input: DoubleHyphen, output: true},
		{name: "should return true for WaveDash", input: WaveDash, output: true},
		{name: "should return true for WavyDash", input: WavyDash, output: true},
		{name: "should return true for KatakanaHiraganaDoubleHyphen", input: KatakanaHiraganaDoubleHyphen, output: true},
		{name: "should return true for PresentationFormForVerticalEmDash", input: PresentationFormForVerticalEmDash, output: true},
		{name: "should return true for PresentationFormForVerticalEnDash", input: PresentationFormForVerticalEnDash, output: true},
		{name: "should return true for SmallEmDash", input: SmallEmDash, output: true},
		{name: "should return true for SmallHyphenMinus", input: SmallHyphenMinus, output: true},
		{name: "should return true for FullwidthHyphenMinus", input: FullwidthHyphenMinus, output: true},
		{name: "should return true for YezidiHyphenationMark", input: YezidiHyphenationMark, output: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, true, false, false, false, false, false))
		})
	}
}

func TestPeUnicodePunctuationsCheck(t *testing.T) {
	tests := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for RightParenthesis", input: RightParenthesis, output: true},
		{name: "should return true for RightSquareBracket", input: RightSquareBracket, output: true},
		{name: "should return true for RightCurlyBracket", input: RightCurlyBracket, output: true},
		{name: "should return true for TibetanMarkGugRtagsGyas", input: TibetanMarkGugRtagsGyas, output: true},
		{name: "should return true for TibetanMarkAngKhangGyas", input: TibetanMarkAngKhangGyas, output: true},
		{name: "should return true for OghamReversedFeatherMark", input: OghamReversedFeatherMark, output: true},
		{name: "should return true for RightSquareBracketwithQuill", input: RightSquareBracketwithQuill, output: true},
		{name: "should return true for SuperscriptRightParenthesis", input: SuperscriptRightParenthesis, output: true},
		{name: "should return true for SubscriptRightParenthesis", input: SubscriptRightParenthesis, output: true},
		{name: "should return true for RightCeiling", input: RightCeiling, output: true},
		{name: "should return true for RightFloor", input: RightFloor, output: true},
		{name: "should return true for RightPointingAngleBracket", input: RightPointingAngleBracket, output: true},
		{name: "should return true for MediumRightParenthesisOrnament", input: MediumRightParenthesisOrnament, output: true},
		{name: "should return true for MediumFlattenedRightParenthesisOrnament", input: MediumFlattenedRightParenthesisOrnament, output: true},
		{name: "should return true for MediumRightPointingAngleBracketOrnament", input: MediumRightPointingAngleBracketOrnament, output: true},
		{name: "should return true for HeavyRightPointingAngleQuotationMarkOrnament", input: HeavyRightPointingAngleQuotationMarkOrnament, output: true},
		{name: "should return true for HeavyRightPointingAngleBracketOrnament", input: HeavyRightPointingAngleBracketOrnament, output: true},
		{name: "should return true for LightRightTortoiseShellBracketOrnament", input: LightRightTortoiseShellBracketOrnament, output: true},
		{name: "should return true for MediumRightCurlyBracketOrnament", input: MediumRightCurlyBracketOrnament, output: true},
		{name: "should return true for RightSShapedBagDelimiter", input: RightSShapedBagDelimiter, output: true},
		{name: "should return true for MathematicalRightWhiteSquareBracket", input: MathematicalRightWhiteSquareBracket, output: true},
		{name: "should return true for MathematicalRightAngleBracket", input: MathematicalRightAngleBracket, output: true},
		{name: "should return true for MathematicalRightDoubleAngleBracket", input: MathematicalRightDoubleAngleBracket, output: true},
		{name: "should return true for MathematicalRightWhiteTortoiseShellBracket", input: MathematicalRightWhiteTortoiseShellBracket, output: true},
		{name: "should return true for MathematicalRightFlattenedParenthesis", input: MathematicalRightFlattenedParenthesis, output: true},
		{name: "should return true for RightWhiteCurlyBracket", input: RightWhiteCurlyBracket, output: true},
		{name: "should return true for RightWhiteParenthesis", input: RightWhiteParenthesis, output: true},
		{name: "should return true for ZNotationRightImageBracket", input: ZNotationRightImageBracket, output: true},
		{name: "should return true for ZNotationRightBindingBracket", input: ZNotationRightBindingBracket, output: true},
		{name: "should return true for RightSquareBracketwithUnderbar", input: RightSquareBracketwithUnderbar, output: true},
		{name: "should return true for RightSquareBracketwithTickInBottomCorner", input: RightSquareBracketwithTickInBottomCorner, output: true},
		{name: "should return true for RightSquareBracketwithTickInTopCorner", input: RightSquareBracketwithTickInTopCorner, output: true},
		{name: "should return true for RightAngleBracketwithDot", input: RightAngleBracketwithDot, output: true},
		{name: "should return true for RightArcGreaterThanBracket", input: RightArcGreaterThanBracket, output: true},
		{name: "should return true for DoubleRightArcLessThanBracket", input: DoubleRightArcLessThanBracket, output: true},
		{name: "should return true for RightBlackTortoiseShellBracket", input: RightBlackTortoiseShellBracket, output: true},
		{name: "should return true for RightWigglyFence", input: RightWigglyFence, output: true},
		{name: "should return true for RightDoubleWigglyFence", input: RightDoubleWigglyFence, output: true},
		{name: "should return true for RightPointingCurvedAngleBracket", input: RightPointingCurvedAngleBracket, output: true},
		{name: "should return true for TopRightHalfBracket", input: TopRightHalfBracket, output: true},
		{name: "should return true for BottomRightHalfBracket", input: BottomRightHalfBracket, output: true},
		{name: "should return true for RightSidewaysUBracket", input: RightSidewaysUBracket, output: true},
		{name: "should return true for RightDoubleParenthesis", input: RightDoubleParenthesis, output: true},
		{name: "should return true for RightAngleBracket", input: RightAngleBracket, output: true},
		{name: "should return true for RightDoubleAngleBracket", input: RightDoubleAngleBracket, output: true},
		{name: "should return true for RightCornerBracket", input: RightCornerBracket, output: true},
		{name: "should return true for RightWhiteCornerBracket", input: RightWhiteCornerBracket, output: true},
		{name: "should return true for RightBlackLenticularBracket", input: RightBlackLenticularBracket, output: true},
		{name: "should return true for RightTortoiseShellBracket", input: RightTortoiseShellBracket, output: true},
		{name: "should return true for RightWhiteLenticularBracket", input: RightWhiteLenticularBracket, output: true},
		{name: "should return true for RightWhiteTortoiseShellBracket", input: RightWhiteTortoiseShellBracket, output: true},
		{name: "should return true for RightWhiteSquareBracket", input: RightWhiteSquareBracket, output: true},
		{name: "should return true for DoublePrimeQuotationMark", input: DoublePrimeQuotationMark, output: true},
		{name: "should return true for LowDoublePrimeQuotationMark", input: LowDoublePrimeQuotationMark, output: true},
		{name: "should return true for OrnateLeftParenthesis", input: OrnateLeftParenthesis, output: true},
		{name: "should return true for PresentationFormForVerticalRightWhiteLenticularBrakcet", input: PresentationFormForVerticalRightWhiteLenticularBrakcet, output: true},
		{name: "should return true for PresentationFormForVerticalRightParenthesis", input: PresentationFormForVerticalRightParenthesis, output: true},
		{name: "should return true for PresentationFormForVerticalRightCurlyBracket", input: PresentationFormForVerticalRightCurlyBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightTortoiseShellBracket", input: PresentationFormForVerticalRightTortoiseShellBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightBlackLenticularBracket", input: PresentationFormForVerticalRightBlackLenticularBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightDoubleAngleBracket", input: PresentationFormForVerticalRightDoubleAngleBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightAngleBracket", input: PresentationFormForVerticalRightAngleBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightCornerBracket", input: PresentationFormForVerticalRightCornerBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightWhiteCornerBracket", input: PresentationFormForVerticalRightWhiteCornerBracket, output: true},
		{name: "should return true for PresentationFormForVerticalRightSquareBracket", input: PresentationFormForVerticalRightSquareBracket, output: true},
		{name: "should return true for SmallRightParenthesis", input: SmallRightParenthesis, output: true},
		{name: "should return true for SmallRightCurlyBracket", input: SmallRightCurlyBracket, output: true},
		{name: "should return true for SmallRightTortoiseShellBracket", input: SmallRightTortoiseShellBracket, output: true},
		{name: "should return true for FullwidthRightParenthesis", input: FullwidthRightParenthesis, output: true},
		{name: "should return true for FullwidthRightSquareBracket", input: FullwidthRightSquareBracket, output: true},
		{name: "should return true for FullwidthRightCurlyBracket", input: FullwidthRightCurlyBracket, output: true},
		{name: "should return true for FullwidthRightWhiteParenthesis", input: FullwidthRightWhiteParenthesis, output: true},
		{name: "should return true for HalfwidthRightCornerBracket", input: HalfwidthRightCornerBracket, output: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, true, false, false, false, false))
		})
	}
}

func TestPfUnicodePunctuationsCheck(t *testing.T) {
	tests := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for RightPointingDoubleAngleQuotationMark", input: RightPointingDoubleAngleQuotationMark, output: true},
		{name: "should return true for RightSingleQuotationMark", input: RightSingleQuotationMark, output: true},
		{name: "should return true for RightDoubleQuotationMark", input: RightDoubleQuotationMark, output: true},
		{name: "should return true for SingleRightPointingAngleQuotationMark", input: SingleRightPointingAngleQuotationMark, output: true},
		{name: "should return true for RightSubstitutionBracket", input: RightSubstitutionBracket, output: true},
		{name: "should return true for RightDottedSubstitutionBracket", input: RightDottedSubstitutionBracket, output: true},
		{name: "should return true for RightTranspositionBracket", input: RightTranspositionBracket, output: true},
		{name: "should return true for RightRaisedOmissionBracket", input: RightRaisedOmissionBracket, output: true},
		{name: "should return true for RightLowParaphraseBracket", input: RightLowParaphraseBracket, output: true},
		{name: "should return true for RightVerticalBarwithQuill", input: RightVerticalBarwithQuill, output: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, true, false, false, false))
		})
	}
}

func TestPiUnicodePunctuationsCheck(t *testing.T) {
	tests := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for LeftPointingDoubleAngleQuotationMark", input: LeftPointingDoubleAngleQuotationMark, output: true},
		{name: "should return true for LeftSingleQuotationMark", input: LeftSingleQuotationMark, output: true},
		{name: "should return true for SingleHighReversed9QuotationMark", input: SingleHighReversed9QuotationMark, output: true},
		{name: "should return true for LeftDoubleQuotationMark", input: LeftDoubleQuotationMark, output: true},
		{name: "should return true for DoubleHighReversed9QuotationMark", input: DoubleHighReversed9QuotationMark, output: true},
		{name: "should return true for SingleLeftPointingAngleQuotationMark", input: SingleLeftPointingAngleQuotationMark, output: true},
		{name: "should return true for LeftSubstitutionBracket", input: LeftSubstitutionBracket, output: true},
		{name: "should return true for LeftDottedSubstitutionBracket", input: LeftDottedSubstitutionBracket, output: true},
		{name: "should return true for LeftTranspositionBracket", input: LeftTranspositionBracket, output: true},
		{name: "should return true for LeftRaisedOmissionBracket", input: LeftRaisedOmissionBracket, output: true},
		{name: "should return true for LeftLowParaphraseBracket", input: LeftLowParaphraseBracket, output: true},
		{name: "should return true for LeftVerticalBarwithQuill", input: LeftVerticalBarwithQuill, output: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, false, true, false, false))
		})
	}
}

func TestPoUnicodePunctuationsCheck(t *testing.T) {
	tests := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for ExclamationMark", input: ExclamationMark, output: true},
		{name: "should return true for QuotationMark", input: QuotationMark, output: true},
		{name: "should return true for NumberSign", input: NumberSign, output: true},
		{name: "should return true for PercentSign", input: PercentSign, output: true},
		{name: "should return true for Ampersand", input: Ampersand, output: true},
		{name: "should return true for Apostrophe", input: Apostrophe, output: true},
		{name: "should return true for Asterisk", input: Asterisk, output: true},
		{name: "should return true for Comma", input: Comma, output: true},
		{name: "should return true for FullStop", input: FullStop, output: true},
		{name: "should return true for Solidus", input: Solidus, output: true},
		{name: "should return true for Colon", input: Colon, output: true},
		{name: "should return true for Semicolon", input: Semicolon, output: true},
		{name: "should return true for QuestionMark", input: QuestionMark, output: true},
		{name: "should return true for CommercialAt", input: CommercialAt, output: true},
		{name: "should return true for ReverseSolidus", input: ReverseSolidus, output: true},
		{name: "should return true for InvertedExclamationMark", input: InvertedExclamationMark, output: true},
		{name: "should return true for SectionSign", input: SectionSign, output: true},
		{name: "should return true for PilcrowSign", input: PilcrowSign, output: true},
		{name: "should return true for MiddleDot", input: MiddleDot, output: true},
		{name: "should return true for InvertedQuestionMark", input: InvertedQuestionMark, output: true},
		{name: "should return true for GreekQuestionMark", input: GreekQuestionMark, output: true},
		{name: "should return true for GreekAnoTeleia", input: GreekAnoTeleia, output: true},
		{name: "should return true for ArmenianApostrophe", input: ArmenianApostrophe, output: true},
		{name: "should return true for ArmenianEmphasisMark", input: ArmenianEmphasisMark, output: true},
		{name: "should return true for ArmenianExclamationMark", input: ArmenianExclamationMark, output: true},
		{name: "should return true for ArmenianComma", input: ArmenianComma, output: true},
		{name: "should return true for ArmenianQuestionMark", input: ArmenianQuestionMark, output: true},
		{name: "should return true for ArmenianAbbreviationMark", input: ArmenianAbbreviationMark, output: true},
		{name: "should return true for ArmenianFullStop", input: ArmenianFullStop, output: true},
		{name: "should return true for HebrewPunctuationPaseq", input: HebrewPunctuationPaseq, output: true},
		{name: "should return true for HebrewPunctuationSofPasuq", input: HebrewPunctuationSofPasuq, output: true},
		{name: "should return true for HebrewPunctuationNunHafukha", input: HebrewPunctuationNunHafukha, output: true},
		{name: "should return true for HebrewPunctuationGeresh", input: HebrewPunctuationGeresh, output: true},
		{name: "should return true for HebrewPunctuationGershayim", input: HebrewPunctuationGershayim, output: true},
		{name: "should return true for ArabicIndicPerMilleSign", input: ArabicIndicPerMilleSign, output: true},
		{name: "should return true for ArabicIndicPerTenThousandSign", input: ArabicIndicPerTenThousandSign, output: true},
		{name: "should return true for ArabicComma", input: ArabicComma, output: true},
		{name: "should return true for ArabicDateSeparator", input: ArabicDateSeparator, output: true},
		{name: "should return true for ArabicSemicolon", input: ArabicSemicolon, output: true},
		{name: "should return true for ArabicTripleDotPunctuationMark", input: ArabicTripleDotPunctuationMark, output: true},
		{name: "should return true for ArabicQuestionMark", input: ArabicQuestionMark, output: true},
		{name: "should return true for ArabicPercentSign", input: ArabicPercentSign, output: true},
		{name: "should return true for ArabicDecimalSeparator", input: ArabicDecimalSeparator, output: true},
		{name: "should return true for ArabicThousandsSeparator", input: ArabicThousandsSeparator, output: true},
		{name: "should return true for ArabicFivePointedStar", input: ArabicFivePointedStar, output: true},
		{name: "should return true for ArabicFullStop", input: ArabicFullStop, output: true},
		{name: "should return true for SyriacEndofParagraph", input: SyriacEndofParagraph, output: true},
		{name: "should return true for SyriacSupralinearFullStop", input: SyriacSupralinearFullStop, output: true},
		{name: "should return true for SyriacSublinearFullStop", input: SyriacSublinearFullStop, output: true},
		{name: "should return true for SyriacSupralinearColon", input: SyriacSupralinearColon, output: true},
		{name: "should return true for SyriacSublinearColon", input: SyriacSublinearColon, output: true},
		{name: "should return true for SyriacHorizontalColon", input: SyriacHorizontalColon, output: true},
		{name: "should return true for SyriacColonSkewedLeft", input: SyriacColonSkewedLeft, output: true},
		{name: "should return true for SyriacColonSkewedRight", input: SyriacColonSkewedRight, output: true},
		{name: "should return true for SyriacSupralinearColonSkewedLeft", input: SyriacSupralinearColonSkewedLeft, output: true},
		{name: "should return true for SyriacSublinearColonSkewedRight", input: SyriacSublinearColonSkewedRight, output: true},
		{name: "should return true for SyriacContraction", input: SyriacContraction, output: true},
		{name: "should return true for SyriacHarkleanObelus", input: SyriacHarkleanObelus, output: true},
		{name: "should return true for SyriacHarkleanMetobelus", input: SyriacHarkleanMetobelus, output: true},
		{name: "should return true for SyriacHarkleanAsteriscus", input: SyriacHarkleanAsteriscus, output: true},
		{name: "should return true for NkoSymbolGbakurunen", input: NkoSymbolGbakurunen, output: true},
		{name: "should return true for NkoComma", input: NkoComma, output: true},
		{name: "should return true for NkoExclamationMark", input: NkoExclamationMark, output: true},
		{name: "should return true for SamaritanPunctuationNequdaa", input: SamaritanPunctuationNequdaa, output: true},
		{name: "should return true for SamaritanPunctuationAfsaaq", input: SamaritanPunctuationAfsaaq, output: true},
		{name: "should return true for SamaritanPunctuationAnged", input: SamaritanPunctuationAnged, output: true},
		{name: "should return true for SamaritanPunctuationBau", input: SamaritanPunctuationBau, output: true},
		{name: "should return true for SamaritanPunctuationAtmaau", input: SamaritanPunctuationAtmaau, output: true},
		{name: "should return true for SamaritanPunctuationShiyyaalaa", input: SamaritanPunctuationShiyyaalaa, output: true},
		{name: "should return true for SamaritanAbbreviationMark", input: SamaritanAbbreviationMark, output: true},
		{name: "should return true for SamaritanPunctuationMelodicQitsa", input: SamaritanPunctuationMelodicQitsa, output: true},
		{name: "should return true for SamaritanPunctuationZiqaa", input: SamaritanPunctuationZiqaa, output: true},
		{name: "should return true for SamaritanPunctuationQitsa", input: SamaritanPunctuationQitsa, output: true},
		{name: "should return true for SamaritanPunctuationZaef", input: SamaritanPunctuationZaef, output: true},
		{name: "should return true for SamaritanPunctuationTuru", input: SamaritanPunctuationTuru, output: true},
		{name: "should return true for SamaritanPunctuationArkaanu", input: SamaritanPunctuationArkaanu, output: true},
		{name: "should return true for SamaritanPunctuationSofMashfaat", input: SamaritanPunctuationSofMashfaat, output: true},
		{name: "should return true for SamaritanPunctuationAnnaau", input: SamaritanPunctuationAnnaau, output: true},
		{name: "should return true for MandaicPunctuation", input: MandaicPunctuation, output: true},
		{name: "should return true for DevanagariDanda", input: DevanagariDanda, output: true},
		{name: "should return true for DevanagariDoubleDanda", input: DevanagariDoubleDanda, output: true},
		{name: "should return true for DevanagariAbbreviationSign", input: DevanagariAbbreviationSign, output: true},
		{name: "should return true for BengaliAbbreviationSign", input: BengaliAbbreviationSign, output: true},
		{name: "should return true for GurmukhiAbbreviationSign", input: GurmukhiAbbreviationSign, output: true},
		{name: "should return true for GujaratiAbbreviationSign", input: GujaratiAbbreviationSign, output: true},
		{name: "should return true for TeluguSignSiddham", input: TeluguSignSiddham, output: true},
		{name: "should return true for KannadaSignSiddham", input: KannadaSignSiddham, output: true},
		{name: "should return true for SinhalaPunctuationKunddaliya", input: SinhalaPunctuationKunddaliya, output: true},
		{name: "should return true for ThaiCharacterFongman", input: ThaiCharacterFongman, output: true},
		{name: "should return true for ThaiCharacterAngkhankhu", input: ThaiCharacterAngkhankhu, output: true},
		{name: "should return true for ThaiCharacterKhomut", input: ThaiCharacterKhomut, output: true},
		{name: "should return true for TibetanMarkInitialYigMgoMdunMa", input: TibetanMarkInitialYigMgoMdunMa, output: true},
		{name: "should return true for TibetanMarkClosingYigMgoSgabMa", input: TibetanMarkClosingYigMgoSgabMa, output: true},
		{name: "should return true for TibetanMarkCaretYigMgoPhurShadMa", input: TibetanMarkCaretYigMgoPhurShadMa, output: true},
		{name: "should return true for TibetanMarkYigMgoTshegShadMa", input: TibetanMarkYigMgoTshegShadMa, output: true},
		{name: "should return true for TibetanMarkSbrulShad", input: TibetanMarkSbrulShad, output: true},
		{name: "should return true for TibetanMarkBskurYigMgo", input: TibetanMarkBskurYigMgo, output: true},
		{name: "should return true for TibetanMarkBkaundefinedShogYigMgo", input: TibetanMarkBkaundefinedShogYigMgo, output: true},
		{name: "should return true for TibetanMarkIntersyllabicTsheg", input: TibetanMarkIntersyllabicTsheg, output: true},
		{name: "should return true for TibetanMarkDelimiterTshegBstar", input: TibetanMarkDelimiterTshegBstar, output: true},
		{name: "should return true for TibetanMarkShad", input: TibetanMarkShad, output: true},
		{name: "should return true for TibetanMarkNyisShad", input: TibetanMarkNyisShad, output: true},
		{name: "should return true for TibetanMarkTshegShad", input: TibetanMarkTshegShad, output: true},
		{name: "should return true for TibetanMarkNyisTshegShad", input: TibetanMarkNyisTshegShad, output: true},
		{name: "should return true for TibetanMarkRinChenSpungsShad", input: TibetanMarkRinChenSpungsShad, output: true},
		{name: "should return true for TibetanMarkRgyaGramShad", input: TibetanMarkRgyaGramShad, output: true},
		{name: "should return true for TibetanMarkGterTsheg", input: TibetanMarkGterTsheg, output: true},
		{name: "should return true for TibetanMarkPaluta", input: TibetanMarkPaluta, output: true},
		{name: "should return true for TibetanMarkBskaundefinedShogGiMgoRgyan", input: TibetanMarkBskaundefinedShogGiMgoRgyan, output: true},
		{name: "should return true for TibetanMarkMnyamYigGiMgoRgyan", input: TibetanMarkMnyamYigGiMgoRgyan, output: true},
		{name: "should return true for TibetanMarkNyisTsheg", input: TibetanMarkNyisTsheg, output: true},
		{name: "should return true for TibetanMarkInitialBrdaRnyingYigMgoMdunMa", input: TibetanMarkInitialBrdaRnyingYigMgoMdunMa, output: true},
		{name: "should return true for TibetanMarkClosingBrdaRnyingYigMgoSgabMa", input: TibetanMarkClosingBrdaRnyingYigMgoSgabMa, output: true},
		{name: "should return true for TibetanMarkLeadingMchanRtags", input: TibetanMarkLeadingMchanRtags, output: true},
		{name: "should return true for TibetanMarkTrailingMchanRtags", input: TibetanMarkTrailingMchanRtags, output: true},
		{name: "should return true for MyanmarSignLittleSection", input: MyanmarSignLittleSection, output: true},
		{name: "should return true for MyanmarSignSection", input: MyanmarSignSection, output: true},
		{name: "should return true for MyanmarSymbolLocative", input: MyanmarSymbolLocative, output: true},
		{name: "should return true for MyanmarSymbolCompleted", input: MyanmarSymbolCompleted, output: true},
		{name: "should return true for MyanmarSymbolAforementioned", input: MyanmarSymbolAforementioned, output: true},
		{name: "should return true for MyanmarSymbolGenitive", input: MyanmarSymbolGenitive, output: true},
		{name: "should return true for GeorgianParagraphSeparator", input: GeorgianParagraphSeparator, output: true},
		{name: "should return true for EthiopicSectionMark", input: EthiopicSectionMark, output: true},
		{name: "should return true for EthiopicWordspace", input: EthiopicWordspace, output: true},
		{name: "should return true for EthiopicFullStop", input: EthiopicFullStop, output: true},
		{name: "should return true for EthiopicComma", input: EthiopicComma, output: true},
		{name: "should return true for EthiopicSemicolon", input: EthiopicSemicolon, output: true},
		{name: "should return true for EthiopicColon", input: EthiopicColon, output: true},
		{name: "should return true for EthiopicPrefaceColon", input: EthiopicPrefaceColon, output: true},
		{name: "should return true for EthiopicQuestionMark", input: EthiopicQuestionMark, output: true},
		{name: "should return true for EthiopicParagraphSeparator", input: EthiopicParagraphSeparator, output: true},
		{name: "should return true for CanadianSyllabicsFullStop", input: CanadianSyllabicsFullStop, output: true},
		{name: "should return true for RunicSinglePunctuation", input: RunicSinglePunctuation, output: true},
		{name: "should return true for RunicMultiplePunctuation", input: RunicMultiplePunctuation, output: true},
		{name: "should return true for RunicCrossPunctuation", input: RunicCrossPunctuation, output: true},
		{name: "should return true for PhilippineSinglePunctuation", input: PhilippineSinglePunctuation, output: true},
		{name: "should return true for PhilippineDoublePunctuation", input: PhilippineDoublePunctuation, output: true},
		{name: "should return true for KhmerSignKhan", input: KhmerSignKhan, output: true},
		{name: "should return true for KhmerSignBariyoosan", input: KhmerSignBariyoosan, output: true},
		{name: "should return true for KhmerSignCamnucPiiKuuh", input: KhmerSignCamnucPiiKuuh, output: true},
		{name: "should return true for KhmerSignBeyyal", input: KhmerSignBeyyal, output: true},
		{name: "should return true for KhmerSignPhnaekMuan", input: KhmerSignPhnaekMuan, output: true},
		{name: "should return true for KhmerSignKoomuut", input: KhmerSignKoomuut, output: true},
		{name: "should return true for MongolianBirga", input: MongolianBirga, output: true},
		{name: "should return true for MongolianEllipsis", input: MongolianEllipsis, output: true},
		{name: "should return true for MongolianComma", input: MongolianComma, output: true},
		{name: "should return true for MongolianFullStop", input: MongolianFullStop, output: true},
		{name: "should return true for MongolianColon", input: MongolianColon, output: true},
		{name: "should return true for MongolianFourDots", input: MongolianFourDots, output: true},
		{name: "should return true for MongolianSibeSyllableBoundaryMarker", input: MongolianSibeSyllableBoundaryMarker, output: true},
		{name: "should return true for MongolianManchuComma", input: MongolianManchuComma, output: true},
		{name: "should return true for MongolianManchuFullStop", input: MongolianManchuFullStop, output: true},
		{name: "should return true for MongolianNirugu", input: MongolianNirugu, output: true},
		{name: "should return true for LimbuExclamationMark", input: LimbuExclamationMark, output: true},
		{name: "should return true for LimbuQuestionMark", input: LimbuQuestionMark, output: true},
		{name: "should return true for BuginesePallawa", input: BuginesePallawa, output: true},
		{name: "should return true for BugineseEndofSection", input: BugineseEndofSection, output: true},
		{name: "should return true for TaiThamSignWiang", input: TaiThamSignWiang, output: true},
		{name: "should return true for TaiThamSignWiangwaak", input: TaiThamSignWiangwaak, output: true},
		{name: "should return true for TaiThamSignSawan", input: TaiThamSignSawan, output: true},
		{name: "should return true for TaiThamSignKeow", input: TaiThamSignKeow, output: true},
		{name: "should return true for TaiThamSignHoy", input: TaiThamSignHoy, output: true},
		{name: "should return true for TaiThamSignDokmai", input: TaiThamSignDokmai, output: true},
		{name: "should return true for TaiThamSignReversedRotatedRana", input: TaiThamSignReversedRotatedRana, output: true},
		{name: "should return true for TaiThamSignKaan", input: TaiThamSignKaan, output: true},
		{name: "should return true for TaiThamSignKaankuu", input: TaiThamSignKaankuu, output: true},
		{name: "should return true for TaiThamSignSatkaan", input: TaiThamSignSatkaan, output: true},
		{name: "should return true for TaiThamSignSatkaankuu", input: TaiThamSignSatkaankuu, output: true},
		{name: "should return true for TaiThamSignHang", input: TaiThamSignHang, output: true},
		{name: "should return true for TaiThamSignCaang", input: TaiThamSignCaang, output: true},
		{name: "should return true for BalinesePanti", input: BalinesePanti, output: true},
		{name: "should return true for BalinesePamada", input: BalinesePamada, output: true},
		{name: "should return true for BalineseWindu", input: BalineseWindu, output: true},
		{name: "should return true for BalineseCarikPamungkah", input: BalineseCarikPamungkah, output: true},
		{name: "should return true for BalineseCarikSiki", input: BalineseCarikSiki, output: true},
		{name: "should return true for BalineseCarikPareren", input: BalineseCarikPareren, output: true},
		{name: "should return true for BalinesePameneng", input: BalinesePameneng, output: true},
		{name: "should return true for BatakSymbolBinduNaMetek", input: BatakSymbolBinduNaMetek, output: true},
		{name: "should return true for BatakSymbolBinduPinarboras", input: BatakSymbolBinduPinarboras, output: true},
		{name: "should return true for BatakSymbolBinduJudul", input: BatakSymbolBinduJudul, output: true},
		{name: "should return true for BatakSymbolBinduPangolat", input: BatakSymbolBinduPangolat, output: true},
		{name: "should return true for LepchaPunctuationTaRol", input: LepchaPunctuationTaRol, output: true},
		{name: "should return true for LepchaPunctuationNyetThyoomTaRol", input: LepchaPunctuationNyetThyoomTaRol, output: true},
		{name: "should return true for LepchaPunctuationCerWa", input: LepchaPunctuationCerWa, output: true},
		{name: "should return true for LepchaPunctuationTshookCerWa", input: LepchaPunctuationTshookCerWa, output: true},
		{name: "should return true for LepchaPunctuationTshook", input: LepchaPunctuationTshook, output: true},
		{name: "should return true for OlChikiPunctuationMucaad", input: OlChikiPunctuationMucaad, output: true},
		{name: "should return true for OlChikiPunctuationDoubleMucaad", input: OlChikiPunctuationDoubleMucaad, output: true},
		{name: "should return true for SundanesePunctuationBinduSurya", input: SundanesePunctuationBinduSurya, output: true},
		{name: "should return true for SundanesePunctuationBinduPanglong", input: SundanesePunctuationBinduPanglong, output: true},
		{name: "should return true for SundanesePunctuationBinduPurnama", input: SundanesePunctuationBinduPurnama, output: true},
		{name: "should return true for SundanesePunctuationBinduCakra", input: SundanesePunctuationBinduCakra, output: true},
		{name: "should return true for SundanesePunctuationBinduLeuSatanga", input: SundanesePunctuationBinduLeuSatanga, output: true},
		{name: "should return true for SundanesePunctuationBinduKaSatanga", input: SundanesePunctuationBinduKaSatanga, output: true},
		{name: "should return true for SundanesePunctuationBinduDaSatanga", input: SundanesePunctuationBinduDaSatanga, output: true},
		{name: "should return true for SundanesePunctuationBinduBaSatanga", input: SundanesePunctuationBinduBaSatanga, output: true},
		{name: "should return true for VedicSignNihshvasa", input: VedicSignNihshvasa, output: true},
		{name: "should return true for DoubleVerticalLine", input: DoubleVerticalLine, output: true},
		{name: "should return true for DoubleLowLine", input: DoubleLowLine, output: true},
		{name: "should return true for Dagger", input: Dagger, output: true},
		{name: "should return true for DoubleDagger", input: DoubleDagger, output: true},
		{name: "should return true for Bullet", input: Bullet, output: true},
		{name: "should return true for TriangularBullet", input: TriangularBullet, output: true},
		{name: "should return true for OneDotLeader", input: OneDotLeader, output: true},
		{name: "should return true for TwoDotLeader", input: TwoDotLeader, output: true},
		{name: "should return true for HorizontalEllipsis", input: HorizontalEllipsis, output: true},
		{name: "should return true for HyphenationPoint", input: HyphenationPoint, output: true},
		{name: "should return true for PerMilleSign", input: PerMilleSign, output: true},
		{name: "should return true for PerTenThousandSign", input: PerTenThousandSign, output: true},
		{name: "should return true for Prime", input: Prime, output: true},
		{name: "should return true for DoublePrime", input: DoublePrime, output: true},
		{name: "should return true for TriplePrime", input: TriplePrime, output: true},
		{name: "should return true for ReversedPrime", input: ReversedPrime, output: true},
		{name: "should return true for ReversedDoublePrime", input: ReversedDoublePrime, output: true},
		{name: "should return true for ReversedTriplePrime", input: ReversedTriplePrime, output: true},
		{name: "should return true for Caret", input: Caret, output: true},
		{name: "should return true for ReferenceMark", input: ReferenceMark, output: true},
		{name: "should return true for DoubleExclamationMark", input: DoubleExclamationMark, output: true},
		{name: "should return true for Interrobang", input: Interrobang, output: true},
		{name: "should return true for Overline", input: Overline, output: true},
		{name: "should return true for CaretInsertionPoint", input: CaretInsertionPoint, output: true},
		{name: "should return true for Asterism", input: Asterism, output: true},
		{name: "should return true for HyphenBullet", input: HyphenBullet, output: true},
		{name: "should return true for DoubleQuestionMark", input: DoubleQuestionMark, output: true},
		{name: "should return true for QuestionExclamationMark", input: QuestionExclamationMark, output: true},
		{name: "should return true for ExclamationQuestionMark", input: ExclamationQuestionMark, output: true},
		{name: "should return true for TironianSignEt", input: TironianSignEt, output: true},
		{name: "should return true for ReversedPilcrowSign", input: ReversedPilcrowSign, output: true},
		{name: "should return true for BlackLeftwardsBullet", input: BlackLeftwardsBullet, output: true},
		{name: "should return true for BlackRightwardsBullet", input: BlackRightwardsBullet, output: true},
		{name: "should return true for LowAsterisk", input: LowAsterisk, output: true},
		{name: "should return true for ReversedSemicolon", input: ReversedSemicolon, output: true},
		{name: "should return true for CloseUp", input: CloseUp, output: true},
		{name: "should return true for TwoAsterisksAlignedVertically", input: TwoAsterisksAlignedVertically, output: true},
		{name: "should return true for SwungDash", input: SwungDash, output: true},
		{name: "should return true for FlowerPunctuationMark", input: FlowerPunctuationMark, output: true},
		{name: "should return true for ThreeDotPunctuation", input: ThreeDotPunctuation, output: true},
		{name: "should return true for QuadruplePrime", input: QuadruplePrime, output: true},
		{name: "should return true for FourDotPunctuation", input: FourDotPunctuation, output: true},
		{name: "should return true for FiveDotPunctuation", input: FiveDotPunctuation, output: true},
		{name: "should return true for TwoDotPunctuation", input: TwoDotPunctuation, output: true},
		{name: "should return true for FourDotMark", input: FourDotMark, output: true},
		{name: "should return true for DottedCross", input: DottedCross, output: true},
		{name: "should return true for Tricolon", input: Tricolon, output: true},
		{name: "should return true for VerticalFourDots", input: VerticalFourDots, output: true},
		{name: "should return true for CopticOldNubianFullStop", input: CopticOldNubianFullStop, output: true},
		{name: "should return true for CopticOldNubianDirectQuestionMark", input: CopticOldNubianDirectQuestionMark, output: true},
		{name: "should return true for CopticOldNubianIndirectQuestionMark", input: CopticOldNubianIndirectQuestionMark, output: true},
		{name: "should return true for CopticOldNubianVerseDivider", input: CopticOldNubianVerseDivider, output: true},
		{name: "should return true for CopticFullStop", input: CopticFullStop, output: true},
		{name: "should return true for CopticMorphologicalDivider", input: CopticMorphologicalDivider, output: true},
		{name: "should return true for TifinaghSeparatorMark", input: TifinaghSeparatorMark, output: true},
		{name: "should return true for RightAngleSubstitutionMarker", input: RightAngleSubstitutionMarker, output: true},
		{name: "should return true for RightAngleDottedSubstitutionMarker", input: RightAngleDottedSubstitutionMarker, output: true},
		{name: "should return true for RaisedInterpolationMarker", input: RaisedInterpolationMarker, output: true},
		{name: "should return true for RaisedDottedInterpolationMarker", input: RaisedDottedInterpolationMarker, output: true},
		{name: "should return true for DottedTranspositionMarker", input: DottedTranspositionMarker, output: true},
		{name: "should return true for RaisedSquare", input: RaisedSquare, output: true},
		{name: "should return true for EditorialCoronis", input: EditorialCoronis, output: true},
		{name: "should return true for Paragraphos", input: Paragraphos, output: true},
		{name: "should return true for ForkedParagraphos", input: ForkedParagraphos, output: true},
		{name: "should return true for ReversedForkedParagraphos", input: ReversedForkedParagraphos, output: true},
		{name: "should return true for Hypodiastole", input: Hypodiastole, output: true},
		{name: "should return true for DottedObelos", input: DottedObelos, output: true},
		{name: "should return true for DownwardsAncora", input: DownwardsAncora, output: true},
		{name: "should return true for UpwardsAncora", input: UpwardsAncora, output: true},
		{name: "should return true for DottedRightPointingAngle", input: DottedRightPointingAngle, output: true},
		{name: "should return true for InvertedInterrobang", input: InvertedInterrobang, output: true},
		{name: "should return true for PalmBranch", input: PalmBranch, output: true},
		{name: "should return true for TildewithRingAbove", input: TildewithRingAbove, output: true},
		{name: "should return true for TildewithDotAbove", input: TildewithDotAbove, output: true},
		{name: "should return true for TildewithDotBelow", input: TildewithDotBelow, output: true},
		{name: "should return true for TwoDotsOverOneDotPunctuation", input: TwoDotsOverOneDotPunctuation, output: true},
		{name: "should return true for OneDotOverTwoDotsPunctuation", input: OneDotOverTwoDotsPunctuation, output: true},
		{name: "should return true for SquaredFourDotPunctuation", input: SquaredFourDotPunctuation, output: true},
		{name: "should return true for FiveDotMark", input: FiveDotMark, output: true},
		{name: "should return true for ReversedQuestionMark", input: ReversedQuestionMark, output: true},
		{name: "should return true for RingPoint", input: RingPoint, output: true},
		{name: "should return true for WordSeparatorMiddleDot", input: WordSeparatorMiddleDot, output: true},
		{name: "should return true for TurnedComma", input: TurnedComma, output: true},
		{name: "should return true for RaisedDot", input: RaisedDot, output: true},
		{name: "should return true for RaisedComma", input: RaisedComma, output: true},
		{name: "should return true for TurnedSemicolon", input: TurnedSemicolon, output: true},
		{name: "should return true for DaggerwithLeftGuard", input: DaggerwithLeftGuard, output: true},
		{name: "should return true for DaggerwithRightGuard", input: DaggerwithRightGuard, output: true},
		{name: "should return true for TurnedDagger", input: TurnedDagger, output: true},
		{name: "should return true for TopHalfSectionSign", input: TopHalfSectionSign, output: true},
		{name: "should return true for StenographicFullStop", input: StenographicFullStop, output: true},
		{name: "should return true for VerticalSixDots", input: VerticalSixDots, output: true},
		{name: "should return true for WigglyVerticalLine", input: WigglyVerticalLine, output: true},
		{name: "should return true for Capitulum", input: Capitulum, output: true},
		{name: "should return true for ReversedComma", input: ReversedComma, output: true},
		{name: "should return true for DashwithLeftUpturn", input: DashwithLeftUpturn, output: true},
		{name: "should return true for DoubleSuspensionMark", input: DoubleSuspensionMark, output: true},
		{name: "should return true for InvertedLowKavyka", input: InvertedLowKavyka, output: true},
		{name: "should return true for InvertedLowKavykawithKavykaAbove", input: InvertedLowKavykawithKavykaAbove, output: true},
	}

	tests_2 := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for LowKavyka", input: LowKavyka, output: true},
		{name: "should return true for LowKavykawithDot", input: LowKavykawithDot, output: true},
		{name: "should return true for DoubleStackedComma", input: DoubleStackedComma, output: true},
		{name: "should return true for DottedSolidus", input: DottedSolidus, output: true},
		{name: "should return true for TripleDagger", input: TripleDagger, output: true},
		{name: "should return true for MedievalComma", input: MedievalComma, output: true},
		{name: "should return true for ParagraphusMark", input: ParagraphusMark, output: true},
		{name: "should return true for PunctusElevatusMark", input: PunctusElevatusMark, output: true},
		{name: "should return true for CornishVerseDivider", input: CornishVerseDivider, output: true},
		{name: "should return true for TironianSignCapitalEt", input: TironianSignCapitalEt, output: true},
		{name: "should return true for IdeographicComma", input: IdeographicComma, output: true},
		{name: "should return true for IdeographicFullStop", input: IdeographicFullStop, output: true},
		{name: "should return true for DittoMark", input: DittoMark, output: true},
		{name: "should return true for PartAlternationMark", input: PartAlternationMark, output: true},
		{name: "should return true for KatakanaMiddleDot", input: KatakanaMiddleDot, output: true},
		{name: "should return true for LisuPunctuationComma", input: LisuPunctuationComma, output: true},
		{name: "should return true for LisuPunctuationFullStop", input: LisuPunctuationFullStop, output: true},
		{name: "should return true for VaiComma", input: VaiComma, output: true},
		{name: "should return true for VaiFullStop", input: VaiFullStop, output: true},
		{name: "should return true for VaiQuestionMark", input: VaiQuestionMark, output: true},
		{name: "should return true for SlavonicAsterisk", input: SlavonicAsterisk, output: true},
		{name: "should return true for CyrillicKavyka", input: CyrillicKavyka, output: true},
		{name: "should return true for BamumNjaemli", input: BamumNjaemli, output: true},
		{name: "should return true for BamumFullStop", input: BamumFullStop, output: true},
		{name: "should return true for BamumColon", input: BamumColon, output: true},
		{name: "should return true for BamumComma", input: BamumComma, output: true},
		{name: "should return true for BamumSemicolon", input: BamumSemicolon, output: true},
		{name: "should return true for BamumQuestionMark", input: BamumQuestionMark, output: true},
		{name: "should return true for PhagsPaSingleHeadMark", input: PhagsPaSingleHeadMark, output: true},
		{name: "should return true for PhagsPaDoubleHeadMark", input: PhagsPaDoubleHeadMark, output: true},
		{name: "should return true for PhagsPaMarkShad", input: PhagsPaMarkShad, output: true},
		{name: "should return true for PhagsPaMarkDoubleShad", input: PhagsPaMarkDoubleShad, output: true},
		{name: "should return true for SaurashtraDanda", input: SaurashtraDanda, output: true},
		{name: "should return true for SaurashtraDoubleDanda", input: SaurashtraDoubleDanda, output: true},
		{name: "should return true for DevanagariSignPushpika", input: DevanagariSignPushpika, output: true},
		{name: "should return true for DevanagariGapFiller", input: DevanagariGapFiller, output: true},
		{name: "should return true for DevanagariCaret", input: DevanagariCaret, output: true},
		{name: "should return true for DevanagariSignSiddham", input: DevanagariSignSiddham, output: true},
		{name: "should return true for KayahLiSignCwi", input: KayahLiSignCwi, output: true},
		{name: "should return true for KayahLiSignShya", input: KayahLiSignShya, output: true},
		{name: "should return true for RejangSectionMark", input: RejangSectionMark, output: true},
		{name: "should return true for JavaneseLeftRerenggan", input: JavaneseLeftRerenggan, output: true},
		{name: "should return true for JavaneseRightRerenggan", input: JavaneseRightRerenggan, output: true},
		{name: "should return true for JavanesePadaAndap", input: JavanesePadaAndap, output: true},
		{name: "should return true for JavanesePadaMadya", input: JavanesePadaMadya, output: true},
		{name: "should return true for JavanesePadaLuhur", input: JavanesePadaLuhur, output: true},
		{name: "should return true for JavanesePadaWindu", input: JavanesePadaWindu, output: true},
		{name: "should return true for JavanesePadaPangkat", input: JavanesePadaPangkat, output: true},
		{name: "should return true for JavanesePadaLingsa", input: JavanesePadaLingsa, output: true},
		{name: "should return true for JavanesePadaLungsi", input: JavanesePadaLungsi, output: true},
		{name: "should return true for JavanesePadaAdeg", input: JavanesePadaAdeg, output: true},
		{name: "should return true for JavanesePadaAdegAdeg", input: JavanesePadaAdegAdeg, output: true},
		{name: "should return true for JavanesePadaPiseleh", input: JavanesePadaPiseleh, output: true},
		{name: "should return true for JavaneseTurnedPadaPiseleh", input: JavaneseTurnedPadaPiseleh, output: true},
		{name: "should return true for JavanesePadaTirtaTumetes", input: JavanesePadaTirtaTumetes, output: true},
		{name: "should return true for JavanesePadaIsenIsen", input: JavanesePadaIsenIsen, output: true},
		{name: "should return true for ChamPunctuationSpiral", input: ChamPunctuationSpiral, output: true},
		{name: "should return true for ChamPunctuationDanda", input: ChamPunctuationDanda, output: true},
		{name: "should return true for ChamPunctuationDoubleDanda", input: ChamPunctuationDoubleDanda, output: true},
		{name: "should return true for ChamPunctuationTripleDanda", input: ChamPunctuationTripleDanda, output: true},
		{name: "should return true for TaiVietSymbolHoHoi", input: TaiVietSymbolHoHoi, output: true},
		{name: "should return true for TaiVietSymbolKoiKoi", input: TaiVietSymbolKoiKoi, output: true},
		{name: "should return true for MeeteiMayekCheikhan", input: MeeteiMayekCheikhan, output: true},
		{name: "should return true for MeeteiMayekAhangKhudam", input: MeeteiMayekAhangKhudam, output: true},
		{name: "should return true for MeeteiMayekCheikhei", input: MeeteiMayekCheikhei, output: true},
		{name: "should return true for PresentationFormForVerticalComma", input: PresentationFormForVerticalComma, output: true},
		{name: "should return true for PresentationFormForVerticalIdeographicComma", input: PresentationFormForVerticalIdeographicComma, output: true},
		{name: "should return true for PresentationFormForVerticalIdeographicFullStop", input: PresentationFormForVerticalIdeographicFullStop, output: true},
		{name: "should return true for PresentationFormForVerticalColon", input: PresentationFormForVerticalColon, output: true},
		{name: "should return true for PresentationFormForVerticalSemicolon", input: PresentationFormForVerticalSemicolon, output: true},
		{name: "should return true for PresentationFormForVerticalExclamationMark", input: PresentationFormForVerticalExclamationMark, output: true},
		{name: "should return true for PresentationFormForVerticalQuestionMark", input: PresentationFormForVerticalQuestionMark, output: true},
		{name: "should return true for PresentationFormForVerticalHorizontalEllipsis", input: PresentationFormForVerticalHorizontalEllipsis, output: true},
		{name: "should return true for PresentationFormForVerticalTwoDotLeader", input: PresentationFormForVerticalTwoDotLeader, output: true},
		{name: "should return true for SesameDot", input: SesameDot, output: true},
		{name: "should return true for WhiteSesameDot", input: WhiteSesameDot, output: true},
		{name: "should return true for DashedOverline", input: DashedOverline, output: true},
		{name: "should return true for CentrelineOverline", input: CentrelineOverline, output: true},
		{name: "should return true for WavyOverline", input: WavyOverline, output: true},
		{name: "should return true for DoubleWavyOverline", input: DoubleWavyOverline, output: true},
		{name: "should return true for SmallComma", input: SmallComma, output: true},
		{name: "should return true for SmallIdeographicComma", input: SmallIdeographicComma, output: true},
		{name: "should return true for SmallFullStop", input: SmallFullStop, output: true},
		{name: "should return true for SmallSemicolon", input: SmallSemicolon, output: true},
		{name: "should return true for SmallColon", input: SmallColon, output: true},
		{name: "should return true for SmallQuestionMark", input: SmallQuestionMark, output: true},
		{name: "should return true for SmallExclamationMark", input: SmallExclamationMark, output: true},
		{name: "should return true for SmallNumberSign", input: SmallNumberSign, output: true},
		{name: "should return true for SmallAmpersand", input: SmallAmpersand, output: true},
		{name: "should return true for SmallAsterisk", input: SmallAsterisk, output: true},
		{name: "should return true for SmallReverseSolidus", input: SmallReverseSolidus, output: true},
		{name: "should return true for SmallPercentSign", input: SmallPercentSign, output: true},
		{name: "should return true for SmallCommercialAt", input: SmallCommercialAt, output: true},
		{name: "should return true for FullwidthExclamationMark", input: FullwidthExclamationMark, output: true},
		{name: "should return true for FullwidthQuotationMark", input: FullwidthQuotationMark, output: true},
		{name: "should return true for FullwidthNumberSign", input: FullwidthNumberSign, output: true},
		{name: "should return true for FullwidthPercentSign", input: FullwidthPercentSign, output: true},
		{name: "should return true for FullwidthAmpersand", input: FullwidthAmpersand, output: true},
		{name: "should return true for FullwidthApostrophe", input: FullwidthApostrophe, output: true},
		{name: "should return true for FullwidthAsterisk", input: FullwidthAsterisk, output: true},
		{name: "should return true for FullwidthComma", input: FullwidthComma, output: true},
		{name: "should return true for FullwidthFullStop", input: FullwidthFullStop, output: true},
		{name: "should return true for FullwidthSolidus", input: FullwidthSolidus, output: true},
		{name: "should return true for FullwidthColon", input: FullwidthColon, output: true},
		{name: "should return true for FullwidthSemicolon", input: FullwidthSemicolon, output: true},
		{name: "should return true for FullwidthQuestionMark", input: FullwidthQuestionMark, output: true},
		{name: "should return true for FullwidthCommercialAt", input: FullwidthCommercialAt, output: true},
		{name: "should return true for FullwidthReverseSolidus", input: FullwidthReverseSolidus, output: true},
		{name: "should return true for HalfwidthIdeographicFullStop", input: HalfwidthIdeographicFullStop, output: true},
		{name: "should return true for HalfwidthIdeographicComma", input: HalfwidthIdeographicComma, output: true},
		{name: "should return true for HalfwidthKatakanaMiddleDot", input: HalfwidthKatakanaMiddleDot, output: true},
		{name: "should return true for AegeanWordSeparatorLine", input: AegeanWordSeparatorLine, output: true},
		{name: "should return true for AegeanWordSeparatorDot", input: AegeanWordSeparatorDot, output: true},
		{name: "should return true for AegeanCheckMark", input: AegeanCheckMark, output: true},
		{name: "should return true for UgariticWordDivider", input: UgariticWordDivider, output: true},
		{name: "should return true for OldPersianWordDivider", input: OldPersianWordDivider, output: true},
		{name: "should return true for CaucasianAlbanianCitationMark", input: CaucasianAlbanianCitationMark, output: true},
		{name: "should return true for ImperialAramaicSectionSign", input: ImperialAramaicSectionSign, output: true},
		{name: "should return true for PhoenicianWordSeparator", input: PhoenicianWordSeparator, output: true},
		{name: "should return true for LydianTriangularMark", input: LydianTriangularMark, output: true},
		{name: "should return true for KharoshthiPunctuationDot", input: KharoshthiPunctuationDot, output: true},
		{name: "should return true for KharoshthiPunctuationSmallCircle", input: KharoshthiPunctuationSmallCircle, output: true},
		{name: "should return true for KharoshthiPunctuationCircle", input: KharoshthiPunctuationCircle, output: true},
		{name: "should return true for KharoshthiPunctuationCrescentBar", input: KharoshthiPunctuationCrescentBar, output: true},
		{name: "should return true for KharoshthiPunctuationMangalam", input: KharoshthiPunctuationMangalam, output: true},
		{name: "should return true for KharoshthiPunctuationLotus", input: KharoshthiPunctuationLotus, output: true},
		{name: "should return true for KharoshthiPunctuationDanda", input: KharoshthiPunctuationDanda, output: true},
		{name: "should return true for KharoshthiPunctuationDoubleDanda", input: KharoshthiPunctuationDoubleDanda, output: true},
		{name: "should return true for KharoshthiPunctuationLines", input: KharoshthiPunctuationLines, output: true},
		{name: "should return true for OldSouthArabianNumericIndicator", input: OldSouthArabianNumericIndicator, output: true},
		{name: "should return true for ManichaeanPunctuationStar", input: ManichaeanPunctuationStar, output: true},
		{name: "should return true for ManichaeanPunctuationFleuron", input: ManichaeanPunctuationFleuron, output: true},
		{name: "should return true for ManichaeanPunctuationDoubleDotWithinDot", input: ManichaeanPunctuationDoubleDotWithinDot, output: true},
		{name: "should return true for ManichaeanPunctuationDotWithinDot", input: ManichaeanPunctuationDotWithinDot, output: true},
		{name: "should return true for ManichaeanPunctuationDot", input: ManichaeanPunctuationDot, output: true},
		{name: "should return true for ManichaeanPunctuationTwoDots", input: ManichaeanPunctuationTwoDots, output: true},
		{name: "should return true for ManichaeanPunctuationLineFiller", input: ManichaeanPunctuationLineFiller, output: true},
		{name: "should return true for AvestanAbbreviationMark", input: AvestanAbbreviationMark, output: true},
		{name: "should return true for TinyTwoDotsOverOneDotPunctuation", input: TinyTwoDotsOverOneDotPunctuation, output: true},
		{name: "should return true for SmallTwoDotsOverOneDotPunctuation", input: SmallTwoDotsOverOneDotPunctuation, output: true},
		{name: "should return true for LargeTwoDotsOverOneDotPunctuation", input: LargeTwoDotsOverOneDotPunctuation, output: true},
		{name: "should return true for LargeOneDotOverTwoDotsPunctuation", input: LargeOneDotOverTwoDotsPunctuation, output: true},
		{name: "should return true for LargeTwoRingsOverOneRingPunctuation", input: LargeTwoRingsOverOneRingPunctuation, output: true},
		{name: "should return true for LargeOneRingOverTwoRingsPunctuation", input: LargeOneRingOverTwoRingsPunctuation, output: true},
		{name: "should return true for PsalterPahlaviSectionMark", input: PsalterPahlaviSectionMark, output: true},
		{name: "should return true for PsalterPahlaviTurnedSectionMark", input: PsalterPahlaviTurnedSectionMark, output: true},
		{name: "should return true for PsalterPahlaviFourDotswithCross", input: PsalterPahlaviFourDotswithCross, output: true},
		{name: "should return true for PsalterPahlaviFourDotswithDot", input: PsalterPahlaviFourDotswithDot, output: true},
		{name: "should return true for SogdianPunctuationTwoVerticalBars", input: SogdianPunctuationTwoVerticalBars, output: true},
		{name: "should return true for SogdianPunctuationTwoVerticalBarswithDots", input: SogdianPunctuationTwoVerticalBarswithDots, output: true},
		{name: "should return true for SogdianPunctuationCirclewithDot", input: SogdianPunctuationCirclewithDot, output: true},
		{name: "should return true for SogdianPunctuationTwoCircleswithDots", input: SogdianPunctuationTwoCircleswithDots, output: true},
		{name: "should return true for SogdianPunctuationHalfCirclewithDot", input: SogdianPunctuationHalfCirclewithDot, output: true},
		{name: "should return true for BrahmiDanda", input: BrahmiDanda, output: true},
		{name: "should return true for BrahmiDoubleDanda", input: BrahmiDoubleDanda, output: true},
		{name: "should return true for BrahmiPunctuationDot", input: BrahmiPunctuationDot, output: true},
		{name: "should return true for BrahmiPunctuationDoubleDot", input: BrahmiPunctuationDoubleDot, output: true},
		{name: "should return true for BrahmiPunctuationLine", input: BrahmiPunctuationLine, output: true},
		{name: "should return true for BrahmiPunctuationCrescentBar", input: BrahmiPunctuationCrescentBar, output: true},
		{name: "should return true for BrahmiPunctuationLotus", input: BrahmiPunctuationLotus, output: true},
		{name: "should return true for KaithiAbbreviationSign", input: KaithiAbbreviationSign, output: true},
		{name: "should return true for KaithiEnumerationSign", input: KaithiEnumerationSign, output: true},
		{name: "should return true for KaithiSectionMark", input: KaithiSectionMark, output: true},
		{name: "should return true for KaithiDoubleSectionMark", input: KaithiDoubleSectionMark, output: true},
		{name: "should return true for KaithiDanda", input: KaithiDanda, output: true},
		{name: "should return true for KaithiDoubleDanda", input: KaithiDoubleDanda, output: true},
		{name: "should return true for ChakmaSectionMark", input: ChakmaSectionMark, output: true},
		{name: "should return true for ChakmaDanda", input: ChakmaDanda, output: true},
		{name: "should return true for ChakmaDoubleDanda", input: ChakmaDoubleDanda, output: true},
		{name: "should return true for ChakmaQuestionMark", input: ChakmaQuestionMark, output: true},
		{name: "should return true for MahajaniAbbreviationSign", input: MahajaniAbbreviationSign, output: true},
		{name: "should return true for MahajaniSectionMark", input: MahajaniSectionMark, output: true},
		{name: "should return true for SharadaDanda", input: SharadaDanda, output: true},
		{name: "should return true for SharadaDoubleDanda", input: SharadaDoubleDanda, output: true},
		{name: "should return true for SharadaAbbreviationSign", input: SharadaAbbreviationSign, output: true},
		{name: "should return true for SharadaSeparator", input: SharadaSeparator, output: true},
		{name: "should return true for SharadaSutraMark", input: SharadaSutraMark, output: true},
		{name: "should return true for SharadaSignSiddham", input: SharadaSignSiddham, output: true},
		{name: "should return true for SharadaContinuationSign", input: SharadaContinuationSign, output: true},
		{name: "should return true for SharadaSectionMark1", input: SharadaSectionMark1, output: true},
		{name: "should return true for SharadaSectionMark2", input: SharadaSectionMark2, output: true},
		{name: "should return true for KhojkiDanda", input: KhojkiDanda, output: true},
		{name: "should return true for KhojkiDoubleDanda", input: KhojkiDoubleDanda, output: true},
		{name: "should return true for KhojkiWordSeparator", input: KhojkiWordSeparator, output: true},
		{name: "should return true for KhojkiSectionMark", input: KhojkiSectionMark, output: true},
		{name: "should return true for KhojkiDoubleSectionMark", input: KhojkiDoubleSectionMark, output: true},
		{name: "should return true for KhojkiAbbreviationSign", input: KhojkiAbbreviationSign, output: true},
		{name: "should return true for MultaniSectionMark", input: MultaniSectionMark, output: true},
		{name: "should return true for NewaDanda", input: NewaDanda, output: true},
		{name: "should return true for NewaDoubleDanda", input: NewaDoubleDanda, output: true},
		{name: "should return true for NewaComma", input: NewaComma, output: true},
		{name: "should return true for NewaGapFiller", input: NewaGapFiller, output: true},
		{name: "should return true for NewaAbbreviationSign", input: NewaAbbreviationSign, output: true},
		{name: "should return true for NewaDoubleComma", input: NewaDoubleComma, output: true},
		{name: "should return true for NewaPlaceholderMark", input: NewaPlaceholderMark, output: true},
		{name: "should return true for NewaInsertionSign", input: NewaInsertionSign, output: true},
		{name: "should return true for TirhutaAbbreviationSign", input: TirhutaAbbreviationSign, output: true},
		{name: "should return true for SiddhamSignSiddham", input: SiddhamSignSiddham, output: true},
		{name: "should return true for SiddhamDanda", input: SiddhamDanda, output: true},
		{name: "should return true for SiddhamDoubleDanda", input: SiddhamDoubleDanda, output: true},
		{name: "should return true for SiddhamSeparatorDot", input: SiddhamSeparatorDot, output: true},
		{name: "should return true for SiddhamSeparatorBar", input: SiddhamSeparatorBar, output: true},
		{name: "should return true for SiddhamRepetitionMark1", input: SiddhamRepetitionMark1, output: true},
		{name: "should return true for SiddhamRepetitionMark2", input: SiddhamRepetitionMark2, output: true},
		{name: "should return true for SiddhamRepetitionMark3", input: SiddhamRepetitionMark3, output: true},
		{name: "should return true for SiddhamEndofTextMark", input: SiddhamEndofTextMark, output: true},
		{name: "should return true for SiddhamSectionMarkwithTridentandUShapedOrnaments", input: SiddhamSectionMarkwithTridentandUShapedOrnaments, output: true},
		{name: "should return true for SiddhamSectionMarkwithTridentandDottedCrescents", input: SiddhamSectionMarkwithTridentandDottedCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithRaysandDottedCrescents", input: SiddhamSectionMarkwithRaysandDottedCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithRaysandDottedDoubleCrescents", input: SiddhamSectionMarkwithRaysandDottedDoubleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithRaysandDottedTripleCrescents", input: SiddhamSectionMarkwithRaysandDottedTripleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkDoubleRing", input: SiddhamSectionMarkDoubleRing, output: true},
		{name: "should return true for SiddhamSectionMarkDoubleRingwithRays", input: SiddhamSectionMarkDoubleRingwithRays, output: true},
		{name: "should return true for SiddhamSectionMarkwithDoubleCrescents", input: SiddhamSectionMarkwithDoubleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithTripleCrescents", input: SiddhamSectionMarkwithTripleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithQuadrupleCrescents", input: SiddhamSectionMarkwithQuadrupleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithSeptupleCrescents", input: SiddhamSectionMarkwithSeptupleCrescents, output: true},
		{name: "should return true for SiddhamSectionMarkwithCirclesandRays", input: SiddhamSectionMarkwithCirclesandRays, output: true},
		{name: "should return true for SiddhamSectionMarkwithCirclesandTwoEnclosures", input: SiddhamSectionMarkwithCirclesandTwoEnclosures, output: true},
		{name: "should return true for SiddhamSectionMarkwithCirclesandFourEnclosures", input: SiddhamSectionMarkwithCirclesandFourEnclosures, output: true},
		{name: "should return true for ModiDanda", input: ModiDanda, output: true},
		{name: "should return true for ModiDoubleDanda", input: ModiDoubleDanda, output: true},
		{name: "should return true for ModiAbbreviationSign", input: ModiAbbreviationSign, output: true},
		{name: "should return true for MongolianBirgawithOrnament", input: MongolianBirgawithOrnament, output: true},
		{name: "should return true for MongolianRotatedBirga", input: MongolianRotatedBirga, output: true},
		{name: "should return true for MongolianDoubleBirgawithOrnament", input: MongolianDoubleBirgawithOrnament, output: true},
		{name: "should return true for MongolianTripleBirgawithOrnament", input: MongolianTripleBirgawithOrnament, output: true},
		{name: "should return true for MongolianBirgawithDoubleOrnament", input: MongolianBirgawithDoubleOrnament, output: true},
		{name: "should return true for MongolianRotatedBirgawithOrnament", input: MongolianRotatedBirgawithOrnament, output: true},
		{name: "should return true for MongolianRotatedBirgawithDoubleOrnament", input: MongolianRotatedBirgawithDoubleOrnament, output: true},
		{name: "should return true for MongolianInvertedBirga", input: MongolianInvertedBirga, output: true},
		{name: "should return true for MongolianInvertedBirgawithDoubleOrnament", input: MongolianInvertedBirgawithDoubleOrnament, output: true},
		{name: "should return true for MongolianSwirlBirga", input: MongolianSwirlBirga, output: true},
		{name: "should return true for MongolianSwirlBirgawithOrnament", input: MongolianSwirlBirgawithOrnament, output: true},
		{name: "should return true for MongolianSwirlBirgawithDoubleOrnament", input: MongolianSwirlBirgawithDoubleOrnament, output: true},
		{name: "should return true for MongolianTurnedSwirlBirgawithDoubleOrnament", input: MongolianTurnedSwirlBirgawithDoubleOrnament, output: true},
		{name: "should return true for AhomSignSmallSection", input: AhomSignSmallSection, output: true},
		{name: "should return true for AhomSignSection", input: AhomSignSection, output: true},
		{name: "should return true for AhomSignRulai", input: AhomSignRulai, output: true},
		{name: "should return true for DograAbbreviationSign", input: DograAbbreviationSign, output: true},
		{name: "should return true for DivesAkuruDoubleDanda", input: DivesAkuruDoubleDanda, output: true},
		{name: "should return true for DivesAkuruGapFiller", input: DivesAkuruGapFiller, output: true},
		{name: "should return true for DivesAkuruEndofTextMark", input: DivesAkuruEndofTextMark, output: true},
		{name: "should return true for NandinagariSignSiddham", input: NandinagariSignSiddham, output: true},
		{name: "should return true for ZanabazarSquareInitialHeadMark", input: ZanabazarSquareInitialHeadMark, output: true},
		{name: "should return true for ZanabazarSquareClosingHeadMark", input: ZanabazarSquareClosingHeadMark, output: true},
		{name: "should return true for ZanabazarSquareMarkTsheg", input: ZanabazarSquareMarkTsheg, output: true},
		{name: "should return true for ZanabazarSquareMarkShad", input: ZanabazarSquareMarkShad, output: true},
		{name: "should return true for ZanabazarSquareMarkDoubleShad", input: ZanabazarSquareMarkDoubleShad, output: true},
		{name: "should return true for ZanabazarSquareMarkLongTsheg", input: ZanabazarSquareMarkLongTsheg, output: true},
		{name: "should return true for ZanabazarSquareInitialDoubleLinedHeadMark", input: ZanabazarSquareInitialDoubleLinedHeadMark, output: true},
		{name: "should return true for ZanabazarSquareClosingDoubleLinedHeadMark", input: ZanabazarSquareClosingDoubleLinedHeadMark, output: true},
		{name: "should return true for SoyomboMarkTsheg", input: SoyomboMarkTsheg, output: true},
		{name: "should return true for SoyomboMarkShad", input: SoyomboMarkShad, output: true},
		{name: "should return true for SoyomboMarkDoubleShad", input: SoyomboMarkDoubleShad, output: true},
		{name: "should return true for SoyomboHeadMarkwithMoonandSunandTripleFlame", input: SoyomboHeadMarkwithMoonandSunandTripleFlame, output: true},
		{name: "should return true for SoyomboHeadMarkwithMoonandSunandFlame", input: SoyomboHeadMarkwithMoonandSunandFlame, output: true},
		{name: "should return true for SoyomboHeadMarkwithMoonandSun", input: SoyomboHeadMarkwithMoonandSun, output: true},
		{name: "should return true for SoyomboTerminalMark1", input: SoyomboTerminalMark1, output: true},
		{name: "should return true for SoyomboTerminalMark2", input: SoyomboTerminalMark2, output: true},
		{name: "should return true for BhaiksukiDanda", input: BhaiksukiDanda, output: true},
		{name: "should return true for BhaiksukiDoubleDanda", input: BhaiksukiDoubleDanda, output: true},
		{name: "should return true for BhaiksukiWordSeparator", input: BhaiksukiWordSeparator, output: true},
		{name: "should return true for BhaiksukiGapFiller1", input: BhaiksukiGapFiller1, output: true},
		{name: "should return true for BhaiksukiGapFiller2", input: BhaiksukiGapFiller2, output: true},
		{name: "should return true for MarchenHeadMark", input: MarchenHeadMark, output: true},
		{name: "should return true for MarchenMarkShad", input: MarchenMarkShad, output: true},
		{name: "should return true for MakasarPassimbang", input: MakasarPassimbang, output: true},
		{name: "should return true for MakasarEndofSection", input: MakasarEndofSection, output: true},
		{name: "should return true for TamilPunctuationEndofText", input: TamilPunctuationEndofText, output: true},
		{name: "should return true for CuneiformPunctuationSignOldAssyrianWordDivider", input: CuneiformPunctuationSignOldAssyrianWordDivider, output: true},
		{name: "should return true for CuneiformPunctuationSignVerticalColon", input: CuneiformPunctuationSignVerticalColon, output: true},
		{name: "should return true for CuneiformPunctuationSignDiagonalColon", input: CuneiformPunctuationSignDiagonalColon, output: true},
		{name: "should return true for CuneiformPunctuationSignDiagonalTricolon", input: CuneiformPunctuationSignDiagonalTricolon, output: true},
		{name: "should return true for CuneiformPunctuationSignDiagonalQuadcolon", input: CuneiformPunctuationSignDiagonalQuadcolon, output: true},
		{name: "should return true for MroDanda", input: MroDanda, output: true},
		{name: "should return true for MroDoubleDanda", input: MroDoubleDanda, output: true},
		{name: "should return true for BassaVahFullStop", input: BassaVahFullStop, output: true},
		{name: "should return true for PahawhHmongSignVosThom", input: PahawhHmongSignVosThom, output: true},
		{name: "should return true for PahawhHmongSignVosTshabCeeb", input: PahawhHmongSignVosTshabCeeb, output: true},
		{name: "should return true for PahawhHmongSignCimCheem", input: PahawhHmongSignCimCheem, output: true},
		{name: "should return true for PahawhHmongSignVosThiab", input: PahawhHmongSignVosThiab, output: true},
		{name: "should return true for PahawhHmongSignVosFeem", input: PahawhHmongSignVosFeem, output: true},
		{name: "should return true for PahawhHmongSignXaus", input: PahawhHmongSignXaus, output: true},
		{name: "should return true for MedefaidrinComma", input: MedefaidrinComma, output: true},
		{name: "should return true for MedefaidrinFullStop", input: MedefaidrinFullStop, output: true},
		{name: "should return true for MedefaidrinSymbolAiva", input: MedefaidrinSymbolAiva, output: true},
		{name: "should return true for MedefaidrinExclamationOh", input: MedefaidrinExclamationOh, output: true},
		{name: "should return true for OldChineseHookMark", input: OldChineseHookMark, output: true},
		{name: "should return true for DuployanPunctuationChinookFullStop", input: DuployanPunctuationChinookFullStop, output: true},
		{name: "should return true for SignwritingComma", input: SignwritingComma, output: true},
		{name: "should return true for SignwritingFullStop", input: SignwritingFullStop, output: true},
		{name: "should return true for SignwritingSemicolon", input: SignwritingSemicolon, output: true},
		{name: "should return true for SignwritingColon", input: SignwritingColon, output: true},
		{name: "should return true for SignwritingParenthesis", input: SignwritingParenthesis, output: true},
		{name: "should return true for AdlamInitialExclamationMark", input: AdlamInitialExclamationMark, output: true},
		{name: "should return true for AdlamInitialQuestionMark", input: AdlamInitialQuestionMark, output: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, false, false, true, false))
		})
	}

	for _, test := range tests_2 {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, false, false, true, false))
		})
	}
}

func TestPsUnicodePunctuationsCheck(t *testing.T) {
	tests := []struct {
		name   string
		input  rune
		output bool
	}{
		{name: "should return true for LeftParenthesis", input: LeftParenthesis, output: true},
		{name: "should return true for LeftSquareBracket", input: LeftSquareBracket, output: true},
		{name: "should return true for LeftCurlyBracket", input: LeftCurlyBracket, output: true},
		{name: "should return true for TibetanMarkGugRtagsGyon", input: TibetanMarkGugRtagsGyon, output: true},
		{name: "should return true for TibetanMarkAngKhangGyon", input: TibetanMarkAngKhangGyon, output: true},
		{name: "should return true for OghamFeatherMark", input: OghamFeatherMark, output: true},
		{name: "should return true for SingleLow9QuotationMark", input: SingleLow9QuotationMark, output: true},
		{name: "should return true for DoubleLow9QuotationMark", input: DoubleLow9QuotationMark, output: true},
		{name: "should return true for LeftSquareBracketwithQuill", input: LeftSquareBracketwithQuill, output: true},
		{name: "should return true for SuperscriptLeftParenthesis", input: SuperscriptLeftParenthesis, output: true},
		{name: "should return true for SubscriptLeftParenthesis", input: SubscriptLeftParenthesis, output: true},
		{name: "should return true for LeftCeiling", input: LeftCeiling, output: true},
		{name: "should return true for LeftFloor", input: LeftFloor, output: true},
		{name: "should return true for LeftPointingAngleBracket", input: LeftPointingAngleBracket, output: true},
		{name: "should return true for MediumLeftParenthesisOrnament", input: MediumLeftParenthesisOrnament, output: true},
		{name: "should return true for MediumFlattenedLeftParenthesisOrnament", input: MediumFlattenedLeftParenthesisOrnament, output: true},
		{name: "should return true for MediumLeftPointingAngleBracketOrnament", input: MediumLeftPointingAngleBracketOrnament, output: true},
		{name: "should return true for HeavyLeftPointingAngleQuotationMarkOrnament", input: HeavyLeftPointingAngleQuotationMarkOrnament, output: true},
		{name: "should return true for HeavyLeftPointingAngleBracketOrnament", input: HeavyLeftPointingAngleBracketOrnament, output: true},
		{name: "should return true for LightLeftTortoiseShellBracketOrnament", input: LightLeftTortoiseShellBracketOrnament, output: true},
		{name: "should return true for MediumLeftCurlyBracketOrnament", input: MediumLeftCurlyBracketOrnament, output: true},
		{name: "should return true for LeftSShapedBagDelimiter", input: LeftSShapedBagDelimiter, output: true},
		{name: "should return true for MathematicalLeftWhiteSquareBracket", input: MathematicalLeftWhiteSquareBracket, output: true},
		{name: "should return true for MathematicalLeftAngleBracket", input: MathematicalLeftAngleBracket, output: true},
		{name: "should return true for MathematicalLeftDoubleAngleBracket", input: MathematicalLeftDoubleAngleBracket, output: true},
		{name: "should return true for MathematicalLeftWhiteTortoiseShellBracket", input: MathematicalLeftWhiteTortoiseShellBracket, output: true},
		{name: "should return true for MathematicalLeftFlattenedParenthesis", input: MathematicalLeftFlattenedParenthesis, output: true},
		{name: "should return true for LeftWhiteCurlyBracket", input: LeftWhiteCurlyBracket, output: true},
		{name: "should return true for LeftWhiteParenthesis", input: LeftWhiteParenthesis, output: true},
		{name: "should return true for ZNotationLeftImageBracket", input: ZNotationLeftImageBracket, output: true},
		{name: "should return true for ZNotationLeftBindingBracket", input: ZNotationLeftBindingBracket, output: true},
		{name: "should return true for LeftSquareBracketwithUnderbar", input: LeftSquareBracketwithUnderbar, output: true},
		{name: "should return true for LeftSquareBracketwithTickInTopCorner", input: LeftSquareBracketwithTickInTopCorner, output: true},
		{name: "should return true for LeftSquareBracketwithTickInBottomCorner", input: LeftSquareBracketwithTickInBottomCorner, output: true},
		{name: "should return true for LeftAngleBracketwithDot", input: LeftAngleBracketwithDot, output: true},
		{name: "should return true for LeftArcLessThanBracket", input: LeftArcLessThanBracket, output: true},
		{name: "should return true for DoubleLeftArcGreaterThanBracket", input: DoubleLeftArcGreaterThanBracket, output: true},
		{name: "should return true for LeftBlackTortoiseShellBracket", input: LeftBlackTortoiseShellBracket, output: true},
		{name: "should return true for LeftWigglyFence", input: LeftWigglyFence, output: true},
		{name: "should return true for LeftDoubleWigglyFence", input: LeftDoubleWigglyFence, output: true},
		{name: "should return true for LeftPointingCurvedAngleBracket", input: LeftPointingCurvedAngleBracket, output: true},
		{name: "should return true for TopLeftHalfBracket", input: TopLeftHalfBracket, output: true},
		{name: "should return true for BottomLeftHalfBracket", input: BottomLeftHalfBracket, output: true},
		{name: "should return true for LeftSidewaysUBracket", input: LeftSidewaysUBracket, output: true},
		{name: "should return true for LeftDoubleParenthesis", input: LeftDoubleParenthesis, output: true},
		{name: "should return true for DoubleLowReversed9QuotationMark", input: DoubleLowReversed9QuotationMark, output: true},
		{name: "should return true for LeftAngleBracket", input: LeftAngleBracket, output: true},
		{name: "should return true for LeftDoubleAngleBracket", input: LeftDoubleAngleBracket, output: true},
		{name: "should return true for LeftCornerBracket", input: LeftCornerBracket, output: true},
		{name: "should return true for LeftWhiteCornerBracket", input: LeftWhiteCornerBracket, output: true},
		{name: "should return true for LeftBlackLenticularBracket", input: LeftBlackLenticularBracket, output: true},
		{name: "should return true for LeftTortoiseShellBracket", input: LeftTortoiseShellBracket, output: true},
		{name: "should return true for LeftWhiteLenticularBracket", input: LeftWhiteLenticularBracket, output: true},
		{name: "should return true for LeftWhiteTortoiseShellBracket", input: LeftWhiteTortoiseShellBracket, output: true},
		{name: "should return true for LeftWhiteSquareBracket", input: LeftWhiteSquareBracket, output: true},
		{name: "should return true for ReversedDoublePrimeQuotationMark", input: ReversedDoublePrimeQuotationMark, output: true},
		{name: "should return true for OrnateRightParenthesis", input: OrnateRightParenthesis, output: true},
		{name: "should return true for PresentationFormForVerticalLeftWhiteLenticularBracket", input: PresentationFormForVerticalLeftWhiteLenticularBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftParenthesis", input: PresentationFormForVerticalLeftParenthesis, output: true},
		{name: "should return true for PresentationFormForVerticalLeftCurlyBracket", input: PresentationFormForVerticalLeftCurlyBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftTortoiseShellBracket", input: PresentationFormForVerticalLeftTortoiseShellBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftBlackLenticularBracket", input: PresentationFormForVerticalLeftBlackLenticularBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftDoubleAngleBracket", input: PresentationFormForVerticalLeftDoubleAngleBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftAngleBracket", input: PresentationFormForVerticalLeftAngleBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftCornerBracket", input: PresentationFormForVerticalLeftCornerBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftWhiteCornerBracket", input: PresentationFormForVerticalLeftWhiteCornerBracket, output: true},
		{name: "should return true for PresentationFormForVerticalLeftSquareBracket", input: PresentationFormForVerticalLeftSquareBracket, output: true},
		{name: "should return true for SmallLeftParenthesis", input: SmallLeftParenthesis, output: true},
		{name: "should return true for SmallLeftCurlyBracket", input: SmallLeftCurlyBracket, output: true},
		{name: "should return true for SmallLeftTortoiseShellBracket", input: SmallLeftTortoiseShellBracket, output: true},
		{name: "should return true for FullwidthLeftParenthesis", input: FullwidthLeftParenthesis, output: true},
		{name: "should return true for FullwidthLeftSquareBracket", input: FullwidthLeftSquareBracket, output: true},
		{name: "should return true for FullwidthLeftCurlyBracket", input: FullwidthLeftCurlyBracket, output: true},
		{name: "should return true for FullwidthLeftWhiteParenthesis", input: FullwidthLeftWhiteParenthesis, output: true},
		{name: "should return true for HalfwidthLeftCornerBracket", input: HalfwidthLeftCornerBracket, output: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			isEqual[bool](t, test.output, IsUnicodePunctuationCharacter(test.input, false, false, false, false, false, false, true))
		})
	}
}
